#!/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bash,bin,ghostty,hooks,hyprland,nvim,starship,tmux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd "$DOTFILES"
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
