#!/bin/bash
pushd "$DOTFILES"

for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g"); do
    echo "Checking $folder"

    if stow -n "$folder" >/dev/null 2>&1; then
        echo "Stowing $folder"
        stow -D "$folder"
        stow "$folder"
    else
        echo "Skipping $folder due to conflicts"
    fi
done

popd
