#!/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,lazygit,nvim,ricing,starship,tmux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
