#!/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,home,i3,lazygit,nvim,rofi,tmux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
